using System.Windows;
using System.Windows.Controls;
using AiComposer.Compilation;
using AiComposer.Contracts;
using AiComposer.Model;
using Base.Core;
using Base.Services;

namespace AiComposer.Runtime;

/// <summary>
/// The single reusable page type behind every generated page. One instance is bound to one page Id
/// and stays alive across edits — only its materialized content (parsed XAML + compiled logic +
/// collectible ALC) is destroyed and recreated. Materialization is lazy: nothing is parsed or
/// compiled until the page is first shown, and compilation runs off the UI thread behind a
/// lightweight placeholder. Any XAML/compile failure renders an inline error panel instead of
/// throwing, so a broken generated page can never crash the app.
/// </summary>
[PageInfo("Generated Page",
	Glyph = "",
	Description = "A page generated by AI Composer.",
	NavOrder = -1)] // negative: excluded from the startup [PageInfo] scan; registered dynamically instead.
public sealed class GeneratedPageHost : Base.Pages.PageBase
{
	private readonly string pageId;

	private bool materialized;
	private string acquiredHash;
	private HostApi hostApi;
	private object logic;

	public GeneratedPageHost(string pageId)
	{
		this.pageId = pageId;
	}

	public string PageId => pageId;

	protected override void OnEnable()
	{
		base.OnEnable();
		if (!materialized)
			_ = MaterializeAsync();
	}

	/// <summary>
	/// Tears down the current materialization (unloading its ALC via the module cache and disposing
	/// its host API) and re-materializes if the page is currently visible. Called on edit so the
	/// nav slot and this instance stay stable while the content is destroyed and recreated.
	/// </summary>
	public void Rematerialize()
	{
		TearDown();
		if (IsEnabled)
			_ = MaterializeAsync();
	}

	/// <summary>Releases all materialized resources. Called by the manager when the page is deleted.</summary>
	public void TearDown()
	{
		materialized = false;

		if (logic is IDisposable disposableLogic)
		{
			try { disposableLogic.Dispose(); } catch { /* generated code — never let teardown throw */ }
		}
		logic = null;

		hostApi?.Dispose();
		hostApi = null;

		if (acquiredHash != null)
		{
			GeneratedPageManager.Instance.ReleaseModule(acquiredHash);
			acquiredHash = null;
		}

		root?.Children.Clear();
	}

	public override void OnDestroy()
	{
		base.OnDestroy();
		TearDown();
	}

	private async Task MaterializeAsync()
	{
		materialized = true; // set eagerly so overlapping OnEnable calls don't double-compile
		ShowPlaceholder();

		GeneratedPageDefinition def = GeneratedPageManager.Instance.LoadDefinition(pageId);
		if (def == null)
		{
			ShowError("Definition not found", [$"No stored definition for page id '{pageId}'."]);
			return;
		}

		string hash = def.SourceHash;
		string asmName = $"GeneratedPage_{def.Id}_{hash[..Math.Min(8, hash.Length)]}";

		CompileOutcome outcome;
		try
		{
			outcome = await Task.Run(() => GeneratedPageManager.Instance.AcquireModule(hash, def.Csharp, asmName));
		}
		catch (Exception ex)
		{
			ShowError("Compilation error", [ex.Message]);
			return;
		}

		if (!outcome.Success)
		{
			ShowError("Could not compile page logic", outcome.Errors);
			return;
		}

		acquiredHash = hash;

		// Back on the UI thread: build the visual tree and wire the logic.
		try
		{
			FrameworkElement ui = XamlMaterializer.Parse(def.Xaml);
			hostApi = new HostApi(def.Title);
			logic = Activator.CreateInstance(outcome.LogicType);

			ui.DataContext = logic;
			((IGeneratedLogic)logic).Initialize(hostApi, ui);

			ui.HorizontalAlignment = HorizontalAlignment.Stretch;
			ui.VerticalAlignment = VerticalAlignment.Stretch;

			root.Children.Clear();
			root.Children.Add(ui);
		}
		catch (Exception ex)
		{
			// Roll back the module acquisition so the ALC can unload if nothing else uses it.
			if (acquiredHash != null)
			{
				GeneratedPageManager.Instance.ReleaseModule(acquiredHash);
				acquiredHash = null;
			}
			hostApi?.Dispose();
			hostApi = null;
			logic = null;
			ShowError("Could not build page UI", [ex.Message]);
		}
	}

	private void ShowPlaceholder()
	{
		root.Children.Clear();
		root.Children.Add(new TextBlock
		{
			Text = "Preparing page…",
			Margin = new Thickness(16),
			Opacity = 0.7,
			HorizontalAlignment = HorizontalAlignment.Center,
			VerticalAlignment = VerticalAlignment.Center,
			Foreground = (System.Windows.Media.Brush)Application.Current.TryFindResource("SystemControlForegroundBaseMediumBrush"),
		});
	}

	private void ShowError(string title, IReadOnlyList<string> details)
	{
		Debug.Log($"[AiComposer] Page '{pageId}' failed: {title}");
		root.Children.Clear();
		root.Children.Add(ErrorPanel.Build(title, details));
	}
}